"""Configuration constants for the Redrob ranker."""

from __future__ import annotations

from datetime import date


REFERENCE_DATE = date(2026, 5, 31)

SERVICE_COMPANIES = {
    "tcs",
    "infosys",
    "wipro",
    "accenture",
    "cognizant",
    "capgemini",
    "hcl",
    "mindtree",
}

PREFERRED_CITIES = {
    "pune",
    "noida",
    "delhi",
    "ncr",
    "hyderabad",
    "mumbai",
    "bangalore",
    "bengaluru",
    "gurugram",
    "gurgaon",
}

PRODUCT_INDUSTRIES = {
    "software",
    "saas",
    "ai/ml",
    "fintech",
    "e-commerce",
    "edtech",
    "adtech",
    "insurance tech",
    "transportation",
    "food delivery",
}

PRODUCT_COMPANIES = {
    "pied piper",
    "hooli",
    "stark industries",
    "wayne enterprises",
    "globex inc",
    "initech",
    "cred",
    "razorpay",
    "zomato",
    "swiggy",
}

DISFAVORED_TITLES = {
    "accountant",
    "business analyst",
    "civil engineer",
    "content writer",
    "customer support",
    "graphic designer",
    "hr manager",
    "marketing manager",
    "mechanical engineer",
    "operations manager",
    "project manager",
    "sales executive",
}

TITLE_WEIGHTS = {
    "senior ai engineer": 1.0,
    "lead ai engineer": 0.98,
    "staff machine learning engineer": 0.96,
    "senior machine learning engineer": 0.95,
    "senior software engineer (ml)": 0.92,
    "applied ml engineer": 0.92,
    "machine learning engineer": 0.9,
    "ai engineer": 0.88,
    "ml engineer": 0.86,
    "senior data scientist": 0.84,
    "data scientist": 0.78,
    "ai research engineer": 0.7,
    "ai specialist": 0.68,
    "senior software engineer": 0.66,
    "backend engineer": 0.62,
    "data engineer": 0.6,
    "analytics engineer": 0.55,
    "software engineer": 0.52,
    "devops engineer": 0.38,
    "cloud engineer": 0.36,
    "full stack developer": 0.34,
}

TERM_GROUPS = {
    "retrieval": {
        "retrieval",
        "information retrieval",
        "semantic search",
        "vector search",
        "hybrid search",
        "search infrastructure",
        "search backend",
        "search & discovery",
        "recommendation system",
        "recommendation systems",
        "recommender",
        "ranking system",
        "ranking systems",
        "candidate matching",
        "matching system",
        "bm25",
        "embeddings",
        "embedding",
        "sentence transformers",
        "vector representations",
    },
    "vector_db": {
        "faiss",
        "milvus",
        "qdrant",
        "weaviate",
        "pinecone",
        "opensearch",
        "elasticsearch",
        "vector database",
        "vector index",
    },
    "llm_nlp": {
        "llm",
        "rag",
        "nlp",
        "transformer",
        "hugging face transformers",
        "fine-tuning llms",
        "fine tuning llms",
        "lora",
        "qlora",
        "peft",
        "bert",
        "gpt",
        "prompt",
    },
    "evaluation": {
        "ndcg",
        "mrr",
        "map",
        "offline benchmark",
        "offline benchmarks",
        "a/b test",
        "a/b testing",
        "evaluation framework",
        "eval framework",
        "ranking evaluation",
        "retrieval quality",
        "regression",
        "feedback loop",
        "recruiter feedback",
    },
    "production": {
        "production",
        "deployed",
        "shipped",
        "real users",
        "scale",
        "latency",
        "monitoring",
        "on-call",
        "on call",
        "index refresh",
        "quality regression",
        "pipeline",
        "pipelines",
        "owned",
        "implemented",
        "built",
    },
    "python_code": {
        "python",
        "pytorch",
        "tensorflow",
        "scikit-learn",
        "sklearn",
        "fastapi",
        "flask",
        "bentoml",
        "mlflow",
        "kubeflow",
        "airflow",
        "spark",
        "kafka",
    },
    "non_target_ai": {
        "computer vision",
        "image classification",
        "speech recognition",
        "tts",
        "robotics",
        "gans",
    },
}

SKILL_PROFICIENCY = {
    "beginner": 0.35,
    "intermediate": 0.6,
    "advanced": 0.82,
    "expert": 1.0,
}

COMPONENT_WEIGHTS = {
    "role_depth": 0.42,
    "production": 0.18,
    "retrieval": 0.12,
    "evaluation": 0.08,
    "seniority": 0.08,
    "product": 0.06,
    "location": 0.06,
}
